2019-12-19 06:11:25,171-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:11:25,409-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:11:35,424-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.241.78.128', port=8010): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCC5679A0>, 'Connection to 223.241.78.128 timed out. (connect timeout=10)'))
2019-12-19 06:11:45,454-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='123.169.168.12', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCC5A7DC0>, 'Connection to 123.169.168.12 timed out. (connect timeout=10)'))
2019-12-19 06:11:55,475-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='115.219.108.241', port=8010): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCC53BF10>, 'Connection to 115.219.108.241 timed out. (connect timeout=10)'))
2019-12-19 06:12:05,493-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='36.248.132.124', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCCDD44F0>, 'Connection to 36.248.132.124 timed out. (connect timeout=10)'))
2019-12-19 06:12:15,513-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='183.166.132.121', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCCDDDC70>, 'Connection to 183.166.132.121 timed out. (connect timeout=10)'))
2019-12-19 06:12:17,734-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='60.167.103.218', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DDCCDD4250>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:12:27,753-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='60.167.135.148', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCC567D90>, 'Connection to 60.167.135.148 timed out. (connect timeout=10)'))
2019-12-19 06:12:37,774-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='183.166.133.73', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCC5A7730>, 'Connection to 183.166.133.73 timed out. (connect timeout=10)'))
2019-12-19 06:12:47,791-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='222.190.163.232', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCC53BF40>, 'Connection to 222.190.163.232 timed out. (connect timeout=10)'))
2019-12-19 06:12:57,811-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.198.24.232', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCCDD46A0>, 'Connection to 223.198.24.232 timed out. (connect timeout=10)'))
2019-12-19 06:13:07,824-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='117.95.110.220', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCCDD4A00>, 'Connection to 117.95.110.220 timed out. (connect timeout=10)'))
2019-12-19 06:13:10,157-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.198.17.48', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DDCC53BBB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:13:21,314-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='121.226.188.204', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCC567910>, 'Connection to 121.226.188.204 timed out. (connect timeout=10)'))
2019-12-19 06:13:31,328-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='117.69.151.243', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCC567A00>, 'Connection to 117.69.151.243 timed out. (connect timeout=10)'))
2019-12-19 06:13:41,342-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='182.35.86.60', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCCDC3C10>, 'Connection to 182.35.86.60 timed out. (connect timeout=10)'))
2019-12-19 06:13:51,355-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.198.19.93', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCCDD4880>, 'Connection to 223.198.19.93 timed out. (connect timeout=10)'))
2019-12-19 06:14:01,369-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='27.152.8.152', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCCDD4FD0>, 'Connection to 27.152.8.152 timed out. (connect timeout=10)'))
2019-12-19 06:14:15,986-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='114.239.29.173', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCCDD4FD0>, 'Connection to 114.239.29.173 timed out. (connect timeout=10)'))
2019-12-19 06:14:18,185-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='114.239.1.194', port=808): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DDCC53BDC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:14:28,204-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.242.246.156', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCCDEC730>, 'Connection to 223.242.246.156 timed out. (connect timeout=10)'))
2019-12-19 06:14:30,440-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='59.57.149.8', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DDCCDD4850>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:14:40,458-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.198.18.61', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCC5A7640>, 'Connection to 223.198.18.61 timed out. (connect timeout=10)'))
2019-12-19 06:14:42,768-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='223.198.7.100', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DDCCDC3910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:14:52,787-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='183.164.238.209', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCCDD4EB0>, 'Connection to 183.164.238.209 timed out. (connect timeout=10)'))
2019-12-19 06:15:02,807-get_ali_keyword-127-INFO:>>>get_keyword error:>>> HTTPConnectionPool(host='117.69.153.185', port=9999): Max retries exceeded with url: http://s.1688.com/company/company_search.htm?keywords=%C4%DA%D2%C2&earseDirect=false&button_click=top&n=y&pageSize=30&beginPage=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001DDCC53B970>, 'Connection to 117.69.153.185 timed out. (connect timeout=10)'))
2019-12-19 06:15:03,339-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:15:03,562-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:15:13,577-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCC53BA30>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:15:15,793-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDD42E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:15:25,807-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDC3640>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:15:35,820-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDD4220>, 'Connection to 180.122.51.24 timed out. (connect timeout=10)'))
2019-12-19 06:15:45,835-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDD4F40>, 'Connection to 183.166.132.200 timed out. (connect timeout=10)'))
2019-12-19 06:15:55,849-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCC567D30>, 'Connection to 117.88.5.126 timed out. (connect timeout=10)'))
2019-12-19 06:16:05,868-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCC53BE80>, 'Connection to 111.79.45.87 timed out. (connect timeout=10)'))
2019-12-19 06:16:15,887-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDC3F10>, 'Connection to 113.12.73.163 timed out. (connect timeout=10)'))
2019-12-19 06:16:25,908-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCC5A74C0>, 'Connection to 117.82.248.126 timed out. (connect timeout=10)'))
2019-12-19 06:16:28,166-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDC3550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:16:38,181-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDD4AF0>, 'Connection to 36.6.146.162 timed out. (connect timeout=10)'))
2019-12-19 06:16:40,367-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop4lb3357596v40.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCC567DC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:16:41,408-get_proxy_ip-51-INFO:>>>get_proxy_ip start
2019-12-19 06:16:41,642-get_proxy_ip-77-INFO:>>>get_proxy_ip end
2019-12-19 06:16:51,656-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCC5A7730>, 'Connection to 117.95.201.237 timed out. (connect timeout=10)'))
2019-12-19 06:16:53,908-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCC5A7FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:17:03,923-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDD33A0>, 'Connection to 114.239.29.211 timed out. (connect timeout=10)'))
2019-12-19 06:17:13,941-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDC3B20>, 'Connection to 180.122.51.24 timed out. (connect timeout=10)'))
2019-12-19 06:17:23,957-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCC5A7700>, 'Connection to 183.166.132.200 timed out. (connect timeout=10)'))
2019-12-19 06:17:33,976-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCC5A7580>, 'Connection to 117.88.5.126 timed out. (connect timeout=10)'))
2019-12-19 06:17:43,989-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCC5A7610>, 'Connection to 111.79.45.87 timed out. (connect timeout=10)'))
2019-12-19 06:17:54,005-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDD3D30>, 'Connection to 113.12.73.163 timed out. (connect timeout=10)'))
2019-12-19 06:18:04,022-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCC53B280>, 'Connection to 117.82.248.126 timed out. (connect timeout=10)'))
2019-12-19 06:18:06,251-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDC3C70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:18:16,267-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDC34C0>, 'Connection to 36.6.146.162 timed out. (connect timeout=10)'))
2019-12-19 06:18:18,517-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCCDD31C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-12-19 06:18:28,529-get_store_phone-175-INFO:>>>get_phone error:>>> HTTPSConnectionPool(host='shop1395248150313.1688.com', port=443): Max retries exceeded with url: /page/contactinfo.htm (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DDCC5A7550>, 'Connection to 182.35.85.125 timed out. (connect timeout=10)'))
